### ISSUE TITLE
Scipt threw an error too

### ISSUE THREAD

**Issue by keyworthgraphics** [robwent/joomla-json-db-check#2]
`Error displaying the error page: Application Instantiation Error: Failed to start the session because headers have already been sent by "/mywebhost/unicleaning/json-db-check.php" at line 36.`

here: [http://www.unimancorp.com/unicleaning/administrator/index.php](url)

**Comment by robwent** [comment]
Hi Will,

I just replied to your mail.

Is Joomla up to date?

I think this might be related to previous Joomla sessions issues.

The script doesn't touch any fields in the sessions table.

Try emptying your sessions table through phpmyadmin (Empty, not drop).

**Comment by keyworthgraphics** [comment]
So, i received a back up and administrator is working again. still not sure how to proceed with the update

**Comment by robwent** [comment]
What was the error that you were seeing after the update?

Can you use the latest version of the script so the line number in the error message matches the current version.

**Comment by tatomixes** [comment]
Dear rob thanks for the help, I have same error when using this script and also have emptied the sessions table, still can make it work.
I have several sites already updated to 3.6.4 and 3.6.3 that doesnt work since joomla update

**Comment by mattsh61** [comment]
Hi!
Have tried to test your script following the instructions on one of my sites that have the error at backend, 'Error decoding JSON data: Syntax error', but going to that file just render at page like this https://github.com/robwent/joomla-json-db-check/blob/master/json-db-check.php Do I have to change some settings on my site? 

Regards
Matt

**Comment by robwent** [comment]
@mattsh61 I'm not sure what you mean. Did you add the script to the root of the site and then view it in a browser?
Please open your own issue as this one is related to session warnings.

**Comment by robwent** [comment]
@tatomixes @keyworthgraphics Have you previously updated your Joomla version through ftp rather than by using the update component?

If you have a backup of the site, can you check in the extensions > database area that the sites database is up to date with your installed Joomla version.

I haven't been able to reproduce this problem.

**Comment by robwent** [comment]
I think this is down to output buffering being disabled.

Can you try this version  and let me know if you get the same error: https://github.com/robwent/joomla-json-db-check/tree/%232

**Comment by tatomixes** [comment]
I have done now the extensions > database after updated joomla to 3.6.4

Now the script works fine and have corrected some tables, then gives me this output:

Row 8 is not valid JSON. Error: (Syntax error)
Content: a:3:{s:6:"action";s:7:"confirm";s:13:"actionbtntext";s:28:"{trans:CONFIRM_SUBSCRIPTION}";s:9:"actionurl";s:19:"{confirm}{/confirm}";}

**Comment by robwent** [comment]
That's a valid serialized array so probably a false positive.

Has the json error gone?

If not, what table did that entry come from?

**Comment by keyworthgraphics** [comment]
the script brought my admin back online. i fixed the database, but still the script is showing a lot of JSON errors

**Comment by robwent** [comment]
They may be false positives.

If the site is working correctly then you can probably delete the script and carry on as normal.

**Comment by keyworthgraphics** [comment]
thank you so much

**Comment by robwent** [comment]
No problem!

**Comment by keyworthgraphics** [comment]
here was my post, and consequently how i got mixed up with you 😎

https://forum.joomla.org/viewtopic.php?p=3438216#p3438216

**Comment by keyworthgraphics** [comment]
hi rob,

all of the recent updates to my sites were made using ftp which annoyed me
to no end. joomla has really gone down the drain...

please check the output from the new file you uploaded:

http://www.unimancorp.com/unicleaning/json-db-check.php?fullcheck=1

**Comment by robwent** [comment]
@keyworthgraphics It's not a good idea to update like that anymore as it won't update your database at the same time.

I know your site is fixed now, but I've seen a few people on LinkedIn and elsewhere saying you should always update through ftp and not listening to anyone (blah blah blah), but that's really bad advice and will get your sites into a lot of trouble in the future if you never visit the extensions > manage> database area.

ftp was only really necessary in 1.5.

For extensions, you should be able to update by either updating through the installer or using the one click update.

**Comment by keyworthgraphics** [comment]
joomla.org says, specifically, "This update cannot be performed through the traditional one-click method, you must update via ftp" - i have found i have MUCH MORE problems, when i forget that, and spend hours troubleshooting and debugging. the update to 3.6.3 WAS a one-button push update, so i thought they had fixed it and when i went to do via one-push, it took down my sites. i agree having to visit the repair database gets old, but how else am i to do it??

**Comment by keyworthgraphics** [comment]
and extensions...most of them, yes, via one-click update, but a lot, including widgetkit, and anything yootheme (don't get me started on their templates...) and anything from rsjoomla (rsform and extensions, etc) have to updated manually by going to their website and downloading the actual zip file...WordPress at least has a system based on using an API to do the updates which i feel is more logical and user friendly. but still, i am very much a joomla fan when it comes to complicated sites. only downside is clients must have a maintenance package in place so everything stays up to date and secure.
