### ISSUE TITLE
How to run the script

### ISSUE THREAD

**Issue by mattsh61** [robwent/joomla-json-db-check#3]
@robwent  That's correct, I did add the script-file to the site root and browsed to it and I just see a page like this https://github.com/robwent/joomla-json-db-check/blob/master/json-db-check.php

Matt

**Comment by robwent** [comment]
If you just see php code then your server is not interpreting php and there is something very wrong.

**Comment by mattsh61** [comment]
Sorry, missed to download raw format, now it works! And the site as well.

@robwent   Thanks for the script!
