### ISSUE TITLE
Warning: Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by 810** [robwent/joomla-json-db-check#5]
Warning: Invalid argument supplied for foreach() in C:\wamp\www\develop\json-db-check.php on line 124

**Comment by robwent** [comment]
Try adding
    var_dump($results);
Above the line mentioned in the error message and see what it says when you run the script again.

What is your php memory set to?

**Comment by 810** [comment]
bool(true) 

256M

**Comment by robwent** [comment]
Ok, that's not much help but would explain why nothing is happening.

This is when you try to check all tables, not the initial check?

What Joomla version and php version are you using?

**Comment by 810** [comment]
nightly huild J3.7.0 and PHP7.1

even with 1gb i get the error

**Comment by robwent** [comment]
I've not tested with 3.7 since it isn't an official release and nightly builds are just for testing... You shouldn't be using it on a production site.
You may need to debug the site yourself manually.

**Comment by robwent** [comment]
I think this was actually down to not having short tags enabled in php.

Try the latest version.

**Comment by 810** [comment]
yes, now the message is gone. thnx

**Comment by robwent** [comment]
I've just added another update so the full check should only show rows that will cause Joomla to throw an error, no false positives.

Can you let us know what it reports?
