### ISSUE TITLE
JSON 

### ISSUE THREAD

**Issue by rlicopoli** [robwent/joomla-json-db-check#8]
If it helps anyone, I was able to correct the 3.6.4 JSON upgrade error by using json-db-check.php:

It found and corrected all of my errors except for one.  The error can manually be repaired by going into the database "extensions" table and "com_languages" column

I changed this:
 
{
"administrator":"\"en-GB\"","site":"\"en-GB\""
}

to this:

{
 "administrator": "\"en-GB\"",
	"site": "\"en-GB\""
}

Everything works again.  json-db-check.php is genius and thank you @robwent or taking the time to share it

**Comment by robwent** [comment]
If you let me know which extension it came from I could start a list of extensions with known problems and then link them to the issues
